checkr/flagr

browser/flagr-ui/README.md

Change UI README to use `yarn`

Update UI README

---

browser/flagr-ui/src/components/Flag.vue

Move form for creating segment into dialog

---

browser/flagr-ui/src/App.vue
browser/flagr-ui/src/components/Flag.vue
browser/flagr-ui/src/components/Flags.vue

Some UI tweaks

---

browser/flagr-ui/src/App.vue
browser/flagr-ui/src/components/Flag.vue
browser/flagr-ui/src/components/Flags.vue
pkg/config/config.go
pkg/entity/flag.go
pkg/handler/crud.go
pkg/handler/eval.go
pkg/handler/eval_cache.go

- Edit flag description
- Edit variant key
- Edit variant attachment
- Showing flag id, variant id and segment id explicitly

Editing variants

---

Dockerfile
Makefile
pkg/entity/flag.go
pkg/entity/segment.go
pkg/entity/variant.go
pkg/handler/crud.go
pkg/handler/eval.go
pkg/util/util.go
pkg/util/util_test.go
swagger/index.yaml
swagger_gen/models/eval_result.go
swagger_gen/restapi/embedded_spec.go

Strong validation around `variantKey`, and also put it on evaluation results so that it's easy to SQL or Query in real-time.

Add variant key validation and put it in the evaluation result

---

browser/flagr-ui/src/App.vue
browser/flagr-ui/src/components/Flag.vue

Add edit segment button

---

Gopkg.lock
Gopkg.toml
pkg/handler/data_recorder_kafka.go
swagger_gen/restapi/configure_flagr.go
vendor/github.com/meatballhat/negroni-logrus/.gitignore
vendor/github.com/meatballhat/negroni-logrus/.travis.yml
vendor/github.com/meatballhat/negroni-logrus/LICENSE
vendor/github.com/meatballhat/negroni-logrus/README.md
vendor/github.com/meatballhat/negroni-logrus/examples/basic/example.go
vendor/github.com/meatballhat/negroni-logrus/examples/custom/example.go
vendor/github.com/meatballhat/negroni-logrus/examples/existinglogrus/example.go
vendor/github.com/meatballhat/negroni-logrus/examples/hooks/example.go
vendor/github.com/meatballhat/negroni-logrus/middleware.go
vendor/github.com/meatballhat/negroni-logrus/middleware_test.go

Fix logrus logging. Previously it was mixed with string and JSON in the stdout. This is to unify them, and always use JSON for stdout via logrus.

Fix logrus and unify all the stdout logging

---

browser/flagr-ui/src/components/Flag.vue

Truncate constraint value and add a tooltip

---

.fsw.yml
browser/flagr-ui/src/App.vue
browser/flagr-ui/src/components/Flag.vue
browser/flagr-ui/src/components/Flags.vue
pkg/repo/db.go

Support constraint editing in place. Instead of removing and adding new constraints, this pr supports directly editing constraint, so that the operation is atomic, and it won't cause inconsistency like delete + add.

Support constraint editing - putConstraint

---

browser/flagr-ui/package.json
browser/flagr-ui/src/App.vue
browser/flagr-ui/src/components/Flag.vue
browser/flagr-ui/src/components/Flags.vue
browser/flagr-ui/src/main.js
browser/flagr-ui/yarn.lock

Bump to element-ui 2.0

---

.fsw.yml
pkg/config/config.go
pkg/handler/eval.go

Use plain text as console stdout, and log data logging with fmt.Println

Change back to string format and only stdout with evalResult

---

browser/flagr-ui/package.json
browser/flagr-ui/src/App.vue
browser/flagr-ui/src/components/DebugConsole.vue
browser/flagr-ui/src/components/Flag.vue
browser/flagr-ui/src/components/Flags.vue
browser/flagr-ui/yarn.lock

Debugging console for better usability
FlagID is auto populated

Add debug console

---

Gopkg.lock
Gopkg.toml
pkg/config/config.go
pkg/handler/data_recorder_kafka.go
pkg/handler/eval_cache.go
pkg/repo/db.go
swagger_gen/restapi/configure_flagr.go
vendor/github.com/evalphobia/logrus_sentry/.travis.yml
vendor/github.com/evalphobia/logrus_sentry/LICENSE
vendor/github.com/evalphobia/logrus_sentry/README.md
vendor/github.com/evalphobia/logrus_sentry/async_test.go
vendor/github.com/evalphobia/logrus_sentry/data_field.go
vendor/github.com/evalphobia/logrus_sentry/data_field_test.go
vendor/github.com/evalphobia/logrus_sentry/sentry.go
vendor/github.com/evalphobia/logrus_sentry/sentry_test.go
vendor/github.com/evalphobia/logrus_sentry/utils.go
vendor/github.com/pkg/errors/.gitignore
vendor/github.com/pkg/errors/.travis.yml
vendor/github.com/pkg/errors/LICENSE
vendor/github.com/pkg/errors/README.md
vendor/github.com/pkg/errors/appveyor.yml
vendor/github.com/pkg/errors/bench_test.go
vendor/github.com/pkg/errors/errors.go
vendor/github.com/pkg/errors/errors_test.go
vendor/github.com/pkg/errors/example_test.go
vendor/github.com/pkg/errors/format_test.go
vendor/github.com/pkg/errors/stack.go
vendor/github.com/pkg/errors/stack_test.go

Setup sentry and more newrelic monitoring

Add sentry and newrelic monitoring

---

pkg/config/config.go
pkg/handler/eval_cache.go

fix nil pointer error b/c we need to construct the new relic client first

Fix new relic client nil pointer error

---

browser/flagr-ui/src/components/Flag.vue

Fix the api change introduced in element 2.0

Fix distribution checkbox

---

browser/flagr-ui/src/components/DebugConsole.vue

Fix the layout of debug console.

Fix debug console layout problem

---

README.md
pkg/entity/fixture.go
pkg/util/util.go

Add go-report card and fix some gofmt issues.

Add go-report card

---

pkg/config/config.go
swagger_gen/restapi/configure_flagr.go

Setting graceful cleanup timeout to 5s, and make it a env variable

Add timeout to graceful server

---

docker-compose.yml
pkg/config/config.go
pkg/entity/distribution_test.go
pkg/entity/entity.go
pkg/entity/fixture.go
pkg/entity/flag.go
pkg/entity/flag_test.go
pkg/entity/segment.go
pkg/entity/segment_test.go
pkg/entity/variant_test.go
pkg/handler/crud.go
pkg/handler/eval_cache.go
pkg/handler/handler.go
pkg/handler/validate.go
pkg/mapper/entity_restapi/e2r/e2r.go
pkg/repo/db.go
pkg/util/util.go
pkg/util/util_test.go

Adding code coverage
- Code coverage improvement for `pkg/entity` package
- Remove unused docker-compose dependency
- Refactor `repo.GetDB()` in `pkg/handler` package

Improve the code coverage

---

docs/README.md
docs/_coverpage.md
docs/api_docs/index.html
docs/index.html

Fix relative URLs

---

browser/flagr-ui/package.json
browser/flagr-ui/src/components/DebugConsole.vue
browser/flagr-ui/src/components/Flag.vue
browser/flagr-ui/src/components/FlagHistory.vue
browser/flagr-ui/yarn.lock
docs/api_docs/bundle.yaml
pkg/mapper/entity_restapi/e2r/e2r.go
swagger/index.yaml
swagger_gen/models/flag_snapshot.go
swagger_gen/restapi/embedded_spec.go

Add UI to show the history

---

browser/flagr-ui/package-lock.json
browser/flagr-ui/package.json
browser/flagr-ui/src/components/FlagHistory.vue
browser/flagr-ui/yarn.lock
pkg/config/env.go
pkg/config/middleware.go

- Fix ejs dependency as the one in nightwatch is not secure
- Fix whitelist prefix path for JWT
- Fix UI to show `no changes` if there's no changes between snapshots

Fix prefix whitelist and no changes snapshots

---

browser/flagr-ui/src/components/FlagHistory.vue
pkg/handler/crud.go
pkg/mapper/entity_restapi/e2r/e2r.go

Fix the preload logic for segments

Fix the preload logic for segments

---

pkg/entity/fixture.go
pkg/entity/flag_test.go
pkg/entity/segment_test.go
pkg/handler/crud.go
pkg/handler/crud_test.go
pkg/handler/jwt.go

crud_test.go unit tests coverage.

Add crud_test unit tests coverage

---

pkg/config/config.go
pkg/config/config_test.go
pkg/config/middleware_test.go
pkg/handler/eval_cache.go
pkg/handler/eval_cache_test.go
pkg/handler/jwt_test.go

Improve unit test coverage for pkg/config and pkg/handler

Increase coverage

---

docs/flagr_env.md
pkg/config/env.go
pkg/config/middleware.go

make the middleware verbose logging configurable.

Add an option for middleware verbose logging

---

Dockerfile
Gopkg.lock
Gopkg.toml

Bump newrelic go-agent and add ca-certificates apk

---

Dockerfile
pkg/repo/db.go

Use fatal instead of panic for db connection problem

---

.circleci/config.yml
Makefile
docs/api_docs/bundle.yaml
pkg/mapper/entity_restapi/e2r/e2r.go
swagger/index.yaml
swagger_gen/models/flag_snapshot.go
swagger_gen/restapi/embedded_spec.go

- Fix test warning from swagger validation
- Use `go test` for test caching natively

Fix test warning

---

Dockerfile

Add `curl` in dockerfile so that it's ready to pull other Flagr instance's export.

Add curl in dockerfile

---

docs/api_docs/bundle.yaml
swagger/export_sqlite.yaml
swagger/health.yaml
swagger_gen/restapi/embedded_spec.go
swagger_gen/restapi/operations/export/get_export_sqlite.go
swagger_gen/restapi/operations/export/get_export_sqlite_parameters.go
swagger_gen/restapi/operations/export/get_export_sqlite_responses.go
swagger_gen/restapi/operations/flagr_api.go
swagger_gen/restapi/operations/health/get_health.go
swagger_gen/restapi/operations/health/get_health_parameters.go
swagger_gen/restapi/operations/health/get_health_responses.go

A quick fix of some descriptions in the API swagger documentation.

Update docs and add operation id

---

browser/flagr-ui/package.json
browser/flagr-ui/src/components/DebugConsole.vue
browser/flagr-ui/src/components/Flag.vue
browser/flagr-ui/src/components/FlagHistory.vue
browser/flagr-ui/src/components/Flags.vue
browser/flagr-ui/src/helpers/helpers.js
browser/flagr-ui/src/main.js
browser/flagr-ui/yarn.lock
docs/api_docs/bundle.yaml
pkg/config/env.go
pkg/config/middleware.go
pkg/mapper/entity_restapi/e2r/e2r.go
swagger/index.yaml
swagger_gen/models/flag.go
swagger_gen/restapi/embedded_spec.go

Generally, improve the UI experience.
- Actually make `flag` and `flagId` in flag.vue reactive
- Change to axios for better error handling
- Correctly handle 307 and 401 JWT authorization errors
- Adding 	`UpdatedAt`, `CreatedBy` and `UpdatedBy` for better homepage filtering (in later pr)

Improve UI

---

Gopkg.lock
pkg/config/env.go
pkg/config/middleware.go
vendor/github.com/phyber/negroni-gzip/LICENSE
vendor/github.com/phyber/negroni-gzip/gzip/gzip.go

Adding gzip to speed up UI's load time.
Tested locally and with rbflagr

Add gzip middleware

---

pkg/entity/flag_snapshot.go
pkg/handler/eval.go
pkg/util/util.go
pkg/util/util_test.go

Add datadog metrics for
- Flag snapshot updated events
- Evaluation

Add dd metrics

---

pkg/handler/eval.go
pkg/handler/eval_test.go

Fix #180 
This pr changed the behavior of segments fall-through logic. The intended behavior wad documented in https://checkr.github.io/flagr/#/flagr_use_cases
New multiple segments with 0% rollout flow.

Fix segments evaluation

---

Makefile
docs/home.md

Fix https://github.com/checkr/flagr/issues/192
- Add `build_ui` in Makefile
- Improve the docs for `development`

Fix Makefile and docs

---

browser/flagr-ui/src/components/Flags.vue

A quick change to support toLowerCase match and use computed instead of watch.

Use lower case and computed for search terms

---

browser/flagr-ui/package-lock.json

Bump eslint

---

Makefile

- Fix https://github.com/checkr/flagr/issues/303

Fix golangci-lint deps

---

browser/flagr-ui/package-lock.json
browser/flagr-ui/package.json

To fix security npm packages:
Ran
```
$ vue upgrade
$ npm audit fix
```
Tested with UI lint and some manual UI testing

Bump npm package and fix security deps

---

browser/flagr-ui/package-lock.json
browser/flagr-ui/package.json
browser/flagr-ui/src/components/Flag.vue

- Fix #324
- Bump minimist to be ">=1.2.2" 
UI tests:
Normal Case:
Invalid Case:

Fix json attachment validation and minimist dependency

---

docs/api_docs/bundle.yaml
swagger/index.yaml
swagger_gen/restapi/doc.go
swagger_gen/restapi/embedded_spec.go

Bump version to 1.1.6

---

browser/flagr-ui/package.json

Update UI version

---

.github/workflows/main.yml

Related to https://github.com/checkr/flagr/issues/292
Wanted to automate the process of docker image publishing to docker hub.

Add publish dockerhub action

---

pkg/handler/crud_test.go

Add a simple unit test that covers https://github.com/checkr/flagr/pull/318

Add 404 get flag test

---

.github/workflows/main.yml

We may need a new step to just publish the `latest` tag. Reference: https://github.com/elgohr/Publish-Docker-Github-Action/issues/70

Add publish to dockerhub with latest tag

---

Makefile
browser/flagr-ui/package.json
browser/flagr-ui/src/App.vue
browser/flagr-ui/src/components/Flag.vue
browser/flagr-ui/src/components/FlagHistory.vue
docs/_coverpage.md
docs/home.md
docs/index.html

- Use dark text on light blue background
- Lessen font size of card headers
- Align navbar header elements to page margins
- Improve spacing on Flag Notes
- Format with prettier
- Add `watch` helper
Fixes #344

Improve UI consistency and contrast

---

pkg/config/config.go
pkg/config/config_test.go
pkg/config/env.go

Introduce the configuration for sentry environment setting. In the future, may want to migrate from `raven-go` to `sentry-go`.
- Added `FLAGR_SENTRY_ENVIRONMENT`
- Refactored some config_test.go with defer setup
unit tests and integration tests.

Add sentry env configuration

---

browser/flagr-ui/package-lock.json
browser/flagr-ui/package.json

Regular bump of npm packages to keep up with the latest changes and patches.
Ran
```
vue upgrade
```

Bump npm packages

---

browser/flagr-ui/package-lock.json
browser/flagr-ui/package.json

Regular bump of UI's package.json and package-lock.json to keep up with the security patches.

Bump npm vendor for UI

---

pkg/config/env.go
pkg/config/middleware.go

fix https://github.com/checkr/flagr/issues/387. I think it makes sense to config CORS for other browser clients.

Add cors env

---

browser/flagr-ui/package-lock.json
browser/flagr-ui/package.json
browser/flagr-ui/src/App.vue
browser/flagr-ui/src/components/DebugConsole.vue
browser/flagr-ui/src/components/Flag.vue
browser/flagr-ui/src/components/FlagHistory.vue
browser/flagr-ui/src/components/Flags.vue
browser/flagr-ui/src/components/MarkdownEditor.vue
browser/flagr-ui/src/components/Spinner.vue

Replace mavon-editor with a simple markdown-it editor. With the minimum setup and a simple katex support. 
Fix https://github.com/checkr/flagr/issues/370
Manual tested the edit/view mode, and the history tracking.

Replace UI flag note markdown editor

---

browser/flagr-ui/package-lock.json
browser/flagr-ui/src/App.vue
browser/flagr-ui/src/components/Flags.vue

- Tweak a little bit of the style of the deleted flags table.
- Add a confirmation message for "restore" button
- Change the font family to match the "flag note"'s github style
Tested locally.

Tweak the style for deleted flags table

---

pkg/config/env.go

Make `/api/v1/health` bypass the auth default so that systems like k8s can do healthz check easily.

Allow /api/v1/health bypass auth default

---

docs/home.md

Fixing a typo in the homepage - `deploymenet` vs. `deployment`.
Fixes a trivial typo.
N/A

Fix typo in home.md
