checkr/flagr

pkg/handler/crud.go
pkg/mapper/entity_restapi/r2e/r2e.go

Add attachment to the variant restapi. Attachment is the dynamic configuration part of the system. For simplicity, only string => string are supported.
```
curl --request POST \
--url http://localhost:18000/api/flags/1/variants \
--header 'content-type: application/json' \
--data '{\n	"key": "treatment",\n	"attachment": {\n		"hi": "321"\n	}\n}'
{
"attachment": {
"hi": "321"
},
"id": 6,
"key": "treatment"
}
curl --request POST \
--url http://localhost:18000/api/flags/1/variants \
--header 'content-type: application/json' \
--data '{\n	"key": "treatment",\n	"attachment": {\n		"hi": 321\n	}\n}'
{
"message": "all key/value pairs should be string/string. invalid attachment format (map[string]interface {}) (len=1) {\n (string) (len=2) \"hi\": (json.Number) (len=3) 321\n}\n"
}
```

Add attachment for variant

---

pkg/handler/crud.go
pkg/handler/validate.go
pkg/util/util.go

Strong validation on `putDistribution`
- Checks sum of percent
- Checks integrity of variants

Strong validation on putDistribution

---

buildscripts/demo.py
docker-compose.yml
pkg/entity/distribution.go
pkg/handler/crud.go
pkg/handler/eval.go
pkg/handler/eval_test.go
pkg/handler/validate.go

Change the variant key should also sync with the distribution's variant key

Change variant key should also change distribution

---

pkg/handler/data_recorder_kafka.go

JSON encode with indent, so that kafka connector can parse

Add JSON indent

---

pkg/entity/flag.go
pkg/handler/crud.go

If the rank of segments are the same, use explicit ID to guarantee the order of the segments

Fix segment stable sort with asc segmentID

---

.circleci/config.yml
Dockerfile-CI
README.md
buildscripts/go-coverage.sh

Add coverage report

---

pkg/entity/segment.go
pkg/handler/crud.go
pkg/handler/eval_cache.go

Use the preload feature from gorm to avoid the n+1 problem
tested with my local, and the gorm debug SQL
```
SELECT * FROM "flags"  WHERE "flags".deleted_at IS NULL[]
SELECT * FROM "segments"  WHERE "segments".deleted_at IS NULL AND (("flag_id" IN (?,?))) ORDER BY Segments.Rank ASC,Segments.Id ASC[1 3]
SELECT * FROM "distributions"  WHERE "distributions".deleted_at IS NULL AND (("segment_id" IN (?,?,?,?,?))) ORDER BY Distributions.variant_id ASC[2 7 8 6 9]
SELECT * FROM "constraints"  WHERE "constraints".deleted_at IS NULL AND (("segment_id" IN (?,?,?,?,?))) ORDER BY Constraints.created_at ASC[2 7 8 6 9]
SELECT * FROM "variants"  WHERE "variants".deleted_at IS NULL AND (("flag_id" IN (?,?)))[1 3]
```

Add eager preload to avoid n+1 problem

---

Gopkg.lock
Gopkg.toml
pkg/util/util.go
pkg/util/util_test.go
vendor/github.com/spf13/cast/.gitignore
vendor/github.com/spf13/cast/.travis.yml
vendor/github.com/spf13/cast/LICENSE
vendor/github.com/spf13/cast/Makefile
vendor/github.com/spf13/cast/README.md
vendor/github.com/spf13/cast/cast.go
vendor/github.com/spf13/cast/cast_test.go
vendor/github.com/spf13/cast/caste.go

To reduce the complexity of util.go, use `spf13/cast` package instead.

Add cast package for safe cast

---

pkg/entity/constraint.go
pkg/handler/eval_test.go

The composition rule requires `()` to group expressions. This fix is targeting segments that have more than two constraints.

Fix constraints composition bug

---

Dockerfile

Use multi-stage build. Requires docker 17.09+.
The image size is down to 40mb.

Use multi-stage build for dockerfile

---

pkg/entity/flag_snapshot.go
pkg/entity/variant.go

Fix postgres string scan bug
The value scanned from postgres is actually with type `string`, not `[]byte`, thus the discrepancy between postgres and other databases.
Fix #101 
Tested with postgres docker environment setup.

Fix postgres string scan bug

---

pkg/config/env.go
pkg/handler/eval.go

Use an env variable `FLAGR_EVAL_LOGGING_ENABLED` to control if we should log the eval result to the console or not.

Use env to config eval logging

---

docs/api_docs/bundle.yaml
pkg/entity/distribution.go
pkg/entity/distribution_test.go
pkg/handler/data_recorder_kafka_test.go
pkg/handler/eval.go
pkg/handler/eval_test.go
swagger/index.yaml
swagger_gen/models/eval_context.go
swagger_gen/models/evaluation_entity.go
swagger_gen/restapi/embedded_spec.go

If `entity_id` is null or empty, flagr will randomly generate one.
Reduce the number of unexpected 422 errors. And also it's convenient for the use case that entity_id is not readily available
Unit test and local integration tests.

Use random entity id if it's nil

---

pkg/config/env.go
pkg/repo/db.go

Since the database connection error may contain credentials, we are adding this env to control whether we should log that error or not.

Add db connection debugging logging env

---

docs/flagr_overview.md

Noticed a typo:
`variantion` -> `variation`

Fix typo in flagr overview docs

---

docs/api_docs/bundle.yaml
swagger/flags.yaml
swagger_gen/restapi/embedded_spec.go
swagger_gen/restapi/operations/flag/find_flags_parameters.go

The default behavior of finding flags is that we find all flags until specifying the limit.

Remove default limit for find flags

---

pkg/handler/data_recorder_kafka.go

From the definition of `InsecureSkipVerify`:
```
// InsecureSkipVerify controls whether a client verifies the     
// server's certificate chain and host name.                     
// If InsecureSkipVerify is true, TLS accepts any certificate    
// presented by the server and any host name in that certificate.
// In this mode, TLS is susceptible to man-in-the-middle attacks.
// This should be used only for testing.                         
```

Fix InsecureVerifySSL config

---

pkg/config/env.go
pkg/config/middleware.go
pkg/config/middleware_test.go

It's more common to use JWT tokens via headers. (e.g: `Authorization Bearer token11`)
Also added the RS256 signing method which is used a lot too.
By default everything works like before 👍 
Manual testing + lot of new UT

Add JWT auth via headers and RS256 signing option

---

pkg/entity/constraint.go

Very minor typo fix on Constraints error prompt
Typo on the word 'wrap'

Fix typo on constraints error alert

---

pkg/config/env.go
pkg/config/middleware.go
pkg/config/middleware_test.go
pkg/handler/eval_cache_test.go

If we set to 401 unauthorized for jwt auth, let the client handles the 401 itself

Fix 401 jwt middleware handling

---

browser/flagr-ui/src/App.vue
browser/flagr-ui/src/components/Flag.vue
browser/flagr-ui/src/components/Flags.vue

Improve homepage UI

---

browser/flagr-ui/src/components/Flags.vue

It looks a bit weird to not have the pointer cursor when clicking on objects that lead to actins or other pages.
For this case, clicking anywhere in the TR element, leads you to edit that flag.
UX

Use pointer cursor for flags table rows

---

pkg/config/env.go
pkg/config/middleware.go

Added `FLAGR_WEB_PREFIX` env so it is possible to serve the static web UI from another path different to `/`
For example, if deploying flagger in ECS behind and ELB it wouldn't be possible to deploy Flagr anywhere but in the `/*` listener since the Web UI is served in `/` and the API in `/api/v1`, this would allow to server the UI from `/web/flagr/*` for example.
Built the code in a docker image, set the environment variable to `/web/flagr` and the UI was loading from that prefix
- [?] My code follows the code style of this project.
- [?] All new and existing tests passed.

Added config for base path for web UI

---

Dockerfile
browser/flagr-ui/config/prod.env.js
browser/flagr-ui/src/components/Flag.vue

Use `FLAGR_UI_POSSIBLE_ENTITY_TYPES` as build arg for UI, by default it's `null`, which means it doesn't imply any restrictions.
To limit the choices and normalize entity types for better data analytics
Tested locally and with docker build-arg

Add UI env for entity types override

---

pkg/handler/crud.go

Fix error
```
{
"message": "cannot find flag entity types. err:Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'key ASC' at line 1"
}
```
Looks like `Order("key ASC")` was not supported in gorm to mysql driver. Since we don't really care about the orders, so just a queryset query is enough

Fix mysql query

---

pkg/config/env.go
pkg/handler/jwt.go

Sometimes the user claim may not be `sub`, so here just make it easy to configure via ENV.

Make user claim configurable

---

.circleci/config.yml
docs/api_docs/bundle.yaml
integration_tests/Dockerfile-Integration-Test
integration_tests/Makefile
integration_tests/docker-compose.yml
integration_tests/test.sh
pkg/handler/crud.go
pkg/handler/eval.go
pkg/handler/eval_test.go
pkg/mapper/entity_restapi/e2r/e2r.go
pkg/mapper/entity_restapi/r2e/r2e.go
swagger/index.yaml
swagger_gen/models/distribution.go
swagger_gen/models/put_variant_request.go
swagger_gen/restapi/doc.go
swagger_gen/restapi/embedded_spec.go

Add integration tests so that we can test flagr against multiple environments or multiple DBs.
To cover DB discrepancies.
Will add more endpoints covered by the swagger API definition.

Add integration tests

---

pkg/config/middleware.go
pkg/config/middleware_test.go
pkg/handler/data_recorder_kafka.go
pkg/handler/data_recorder_kafka_test.go

Reorder the middleware so that other stats logging can catch recovery middleware.
- Move recovery middleware closer to the application code
- Use logrus for recovery middleware logging, so that it can catch recovery error in sentry
- Add tests for `mustParseKafkaVersion`

Reorder middlewares and add test for must parse kafka version

---

docs/api_docs/bundle.yaml
integration_tests/test.sh
pkg/entity/flag.go
pkg/entity/segment.go
pkg/handler/crud.go
pkg/handler/crud_test.go
pkg/handler/eval_cache.go
pkg/mapper/entity_restapi/e2r/e2r.go
swagger/flags.yaml
swagger_gen/restapi/embedded_spec.go
swagger_gen/restapi/operations/flag/find_flags_parameters.go
swagger_gen/restapi/operations/flag/find_flags_urlbuilder.go

Add preload query param in `GET /flags`. Fix #199 
- `GET /flags?preload=true` to get all the segments and variants together with the flags.
- Refactor the existing code of preloading for both flags (+segments +variants) and segments (+constraints +distributions)
- Simplify how we do the mapper of entity-to-restapi (e2r), removed the param of preload flag, and let its upstream call preload function before the mapper

Add preload param in get /flags

---

browser/flagr-ui/src/components/Flag.vue

Text change to the flagr UI. This is intended to make it less confusing for first time users to create constraints.
Before
After

Replace '+' icon with 'Add Constraint' to make usage clearer

---

pkg/handler/eval.go
pkg/handler/eval_test.go

Some old clients are validating flag_id in the response. If a flag was deleted, the response should still pass the `flag_id >= 1` validation rule defined in swagger.
unit tests and integration tests

Fix empty response when flag was deleted

---

browser/flagr-ui/config/index.js

assetsPublicPath needs to be relative, so that it can work with `FLAGR_WEB_PREFIX='/foo'`
tested locally with and without the `FLAGR_WEB_PREFIX` setting.
```
FLAGR_WEB_PREFIX='/foo' make run
```
```
make run
```

Use relative assetsPublicPath

---

browser/flagr-ui/src/main.js

As the contents for flagr is in English, set the default locale for
ElementUI to English (instead of defaulting to Chinese).  This is to
prevent certain contents from being displayed in Chinese.  eg. when
there are no flags available.
Keep the language consistent in the application.
Launch the default flagr and run it using docker:
Before the change, confirm that the bug is present by launching a docker container as such:
```
docker run -p 18000:18000 checkr/flagr
```
Visit the GUI and delete all flags.  You will see `No Data` in Chinese written as `暂无数据`.
Test the change and launch a docker container with the change.  You will see `No Data`.

Use English as default locale for flagr instead of Chinese

---

pkg/config/env.go
pkg/handler/data_record_frame.go
pkg/handler/data_record_frame_test.go
pkg/handler/data_recorder.go
pkg/handler/data_recorder_kafka.go
pkg/handler/data_recorder_kafka_test.go
pkg/handler/data_recorder_kinesis.go
pkg/handler/data_recorder_kinesis_test.go
pkg/handler/data_recorder_pubsub.go
pkg/handler/data_recorder_pubsub_test.go
pkg/handler/eval.go

Fix #232 #203 
- Refactor all data recorders
- Add data_record_frame.go
- Change the interface of DataRecorder to comply with DataRecordFrame
- Add the option to set the output mode of DataRecordFrame
- Consolidate and simplify adding new data recorders
Tested locally, note that `kt` tool prints the value field of kafka messages with escape.
```
FLAGR_RECORDER_ENABLED=true FLAGR_RECORDER_FRAME_OUTPUT_MODE=payload_raw_json make run
kt consume -topic flagr-records -offsets all=newest-1:
{
"partition": 0,
"offset": 8,
"key": "a1234",
"value": "{\"payload\":{\"evalContext\":{\"enableDebug\":true,\"entityContext\":{\"hello\":\"world\"},\"entityID\":\"a1234\",\"entityType\":\"a123\",\"flagID\":1,\"flagKey\":\"kmmcd1nsd6\"},\"evalDebugLog\":{\"segmentDebugLogs\":[{\"msg\":\"argument: state not …
```

Refactor data recorder

---

pkg/config/env.go
pkg/handler/eval.go

Fix #228
Add an option so that we can disable evaluation debug globally due to security reasons. By default, it's enabled.

Add EvalDebugEnabled env variable

---

docs/api_docs/bundle.yaml
pkg/config/middleware_test.go
pkg/handler/data_record_frame_test.go
pkg/handler/data_recorder_kinesis.go
pkg/handler/data_recorder_kinesis_test.go
pkg/handler/data_recorder_pubsub_test.go
pkg/handler/eval.go
pkg/handler/eval_test.go
swagger/index.yaml
swagger_gen/models/eval_result.go
swagger_gen/restapi/embedded_spec.go

This caused an issue under the following circumstance:
* A flag did not exist in flagr
* The consumer requested a flag by only specifying `:flag_key`
* Flagr returned a 200 response with `:flag_id` omitted
* The ruby code generated by swagger raised an `ArgumentError` because the response from the server was missing `:flag_id`
Ultimately, it's up to the consumer app anyway to decide what it requires from the server response, not the HTTP interface library.
Unit test and integration tests

Remove required fields from evalResult swagger model

---

browser/flagr-ui/config/prod.env.js
pkg/config/env.go
pkg/config/middleware.go

Fix #225. Context is that UI's api path can be relative, and we can also prefix our main api with `FLAGR_WEB_PREFIX`
Tested locally with and without `FLAGR_WEB_PREFIX`
Although breaking changes to the behavior of FLAGR_WEB_PREFIX, but the scope should be small, since it only applies to deployment after https://github.com/checkr/flagr/issues/222

Use web prefix for main API

---

pkg/handler/eval.go

`r.EvalContext.EntityType` has really high cardinality, removing it to save the datadog's 1k per metric limit.

Remove entity_type statsd tag

---

pkg/handler/handler.go

If `RecorderEnabled` is true, try to call `GetDataRecorder()` early to catch fatal errors early instead of during the evaluation time.
Related to #244

Call data recorder at the startup time

---

browser/flagr-ui/package.json
browser/flagr-ui/src/components/Flag.vue
browser/flagr-ui/src/components/MarkdownEditor.vue
browser/flagr-ui/yarn.lock
docs/api_docs/bundle.yaml
pkg/entity/flag.go
pkg/handler/crud.go
pkg/handler/crud_test.go
pkg/mapper/entity_restapi/e2r/e2r.go
swagger/index.yaml
swagger_gen/models/flag.go
swagger_gen/models/put_flag_request.go
swagger_gen/restapi/embedded_spec.go

Related to issue #230
Adds a new notes section to the flag config view and updates the API to allow for adding a flag with attached notes in markdown format. Notes can be used for adding details about flag usage, describing the flag's purpose, adding examples of usage, etc.
Collapsed view when no notes are present:
Editor view:
View when notes present:
This solves the inconvenience of having to have separate, hard-to-find documentation pages for a given flag. Instead, all relevant documentation is held on the flag config page itself.
Manual UI testing and updated CRUD tests to check for new field acceptance.

add note support to flags

---

browser/flagr-ui/src/App.vue

this ensures that h2 text within cards does not become unreadable. resolves an issue where h2s within flag notes are displayed as white text on a white background

ensure header color css applies only within el-card__header

---

pkg/config/config.go
pkg/config/env.go

Adds the ability to use the Logrus JSONFormatter.
Allows for simple end-to-end structured logging via Docker -> Fluentd -> ElasticSearch.
Tested manually. Ensured new and default behavior.

Add ability to output logs in JSON format

---

pkg/entity/flag_test.go
pkg/handler/crud_test.go
pkg/util/util.go
pkg/util/util_test.go

Allowing capital letters and numbers in flag keys and variant keys. This helps with use cases where keys are being migrated from legacy systems to flagr.
Change flag key regex to accommodate to allow any word character, digits and hyphen.
This resolves issue 254. 
https://github.com/checkr/flagr/issues/254
Changed unit tests and tested locally by creating keys with capital letters and digits and other combinations.

Allow more capital characters and numbers in flag keys and variant keys

---

browser/flagr-ui/package.json
browser/flagr-ui/yarn.lock

Bump webpack-bundle-analyzer

---

pkg/entity/fixture.go
pkg/entity/variant.go
pkg/handler/crud_test.go
pkg/mapper/entity_restapi/r2e/r2e.go

Allow storing arbitrary JSON structures within variants' attachment field
Update the Attachment field type from map[string]string to map[string]interface{}
Enable using flagr as a smart general configuration store and remove hacks that use strings in order to store structured data
The existing tests were updated to accommodate for this change

Add support for arbitrary JSON in attachments

---

browser/flagr-ui/src/components/DebugConsole.vue
browser/flagr-ui/src/components/Flag.vue

In order to edit easily the variant attachment, I replaced the existing input to the same json editor that used in the evaluator on the same page.
I was trying to use flagr with a variant that has more than one key and found myself struggling with the input area. The existing input area was designed for using simple texts in forms, such as name or email, but not JSON.
In order to edit JSON, with syntax highlighting and auto-correct, out of the box, I found my self use the same component that was used on the same page.
Tested locally, manually.

Changed input text to json-editor in flag variant form

---

browser/flagr-ui/public/index.html
browser/flagr-ui/vue.config.js

To keep the same `static` assetsDir as before.

Fix assetsDir

---

browser/flagr-ui/src/components/Flag.vue

As part of improving the existing UI, we replaced the existing variant attachment input with json-editor. In this PR there was a bug which set the height of that container and causes it to look bad when it should expand.
This change is required in order to have a better look and feel. It solves the mentioned styling issue.
Before:
After:
Manually, locally.

Height fix for json-editor in variant attachment

---

browser/flagr-ui/src/components/Flags.vue

I added a search bar that can help to find a flag throw a big number of flags on the home page.
When the usage of flagr grows, I tend to add more flags for every configuration I have. By doing that, I affect directly the length of the list of flags on the home page. I was trying to suggest a new way to navigate throw all the flags easily.
Tested locally, manually.

Add search bar for filtering flags in home page

---

browser/flagr-ui/src/components/Flag.vue

A small fix for having correct deleted flag id instead of undefined.
Manually, locally.

bugfix: "You deleted flag undefined"

---

.circleci/config.yml
Dockerfile
integration_tests/Dockerfile-Integration-Test

`libc6-compat` looks not working correctly in the circleci environment. `fnctl64 not found` was thrown in the new integration tests and alpine 3.6 images.
Wanna test if bumping the alpine to 3.10 with glibc and the remote docker engine can solve the error of https://circleci.com/gh/checkr/flagr/907
Specifically, https://hub.docker.com/r/frolvlad/alpine-glibc and https://github.com/frol/docker-alpine-glibc is a popular alpine glibc base image to get started.

Use alpine 3.10 with glibc and bump remote docker in ciecleci

---

docs/flagr_use_cases.md

Update Dynamic Configuration section to match the variant attachment format updates introduced in #259 
Documentation.
- [docsify](https://docsify.js.org/#/)

docs: update Dynamic Configuration section

---

pkg/config/env.go
pkg/config/middleware.go
pkg/config/middleware_test.go

Added support for validating HS512 JWT tokens
added a hs512 case to handle the tokens
We have JWT tokens signed by HS512 method. Its was throwing invalid signature. So had to add this extension
I have added tests with valid HS512 signed tokens

added support for validating HS512 JWT tokens

---

Makefile
docs/api_docs/bundle.yaml
integration_tests/test.sh
pkg/handler/crud.go
pkg/handler/crud_test.go
pkg/handler/eval.go
pkg/handler/eval_test.go
swagger/export_sqlite.yaml
swagger_gen/models/evaluation_batch_request.go
swagger_gen/models/put_segment_reorder_request.go
swagger_gen/restapi/configure_flagr.go
swagger_gen/restapi/embedded_spec.go
swagger_gen/restapi/operations/export/get_export_sqlite_parameters.go
swagger_gen/restapi/operations/flag/find_flags_urlbuilder.go
swagger_gen/restapi/server.go

Bump to latest go-swagger@0.20.1. Fixed some breaking changes. Note that there are no changes to the flagr APIs at all. Just some variables renaming internally.
Fix https://github.com/checkr/flagr/issues/283

Bump go-swagger

---

browser/flagr-ui/src/components/Flag.vue

Fix UI for constraint deletion

---

pkg/config/env.go

The provided example string was not working for me with Postgres.
I propose one that works.
It helps to start running Flagr with Postgres quickly 
Tested manually on local machine in docker compose env

Change Postgres connection string example

---

pkg/handler/eval.go
pkg/handler/eval_test.go

In order to use flagr as a go package, EvalFlag should be public.
ref #298
I put evalFlag public
As I work with flagr as a go package, to implement my own evaluator base on flagr solution. EvalFlag was the only function that needed to be public and was not. (see #298 )
The test have been updated, but they don;t need to be changed

feat: Put EvalFlag public

---

Makefile

Fix https://github.com/checkr/flagr/issues/309

Fix swagger version

---

pkg/config/middleware.go

Removes a stray `fmt.Println` from the Prometheus middleware.
With the Prometheus middleware enabled (using the Docker image with `FLAGR_PROMETHEUS_ENABLED="true"`), this is flooding our logs with float values like:
```
0.000139925
0.000169531
0.000258753
0.000200045
0.000197314
0.00013287
0.000159397
7.7382e-05
0.000159737
... etc
```
Built and deployed a canary Docker image with this change, checked that the values were no longer being output to stdout.

Remove fmt.Println from Prometheus middleware

---

pkg/util/util.go
pkg/util/util_test.go

Upstream issue: https://github.com/checkr/flagr/issues/315
Allows you to add a as a valid character in a flag name to allow for sensible namespacing
Allows people to namespace in a unix type fashion that makes it clear where the namespace ends and the flag begins
Tested locally against existing postgres database; was able to update a flag and then get the flag back successfully

Allow slashes in the flag name regex

---

pkg/config/config.go
pkg/config/env.go

Add ability to enable newrelic's distributed tracing
This is a feature within newrelic's agent that is by default off and the only way to enable on go agent is by setting in the config, the other method with the env `NEW_RELIC_DISTRIBUTED_TRACING_ENABLED=true` won't work as the go agent doesn't read env variables.
I've deployed the docker image with the changes a server and checked newrelic's distributed tracing and they showed up.

Add ability to enable newrelic's distributed tracing

---

Makefile
pkg/handler/subject_test.go

Fix golangci-lint:
```
#!/bin/bash -eo pipefail
make ci
Running verify_lint
pkg/handler/subject_test.go:26:31: SA1029: should not use built-in type string as key for value; define your own type to avoid collisions (staticcheck)
ctx = context.WithValue(ctx, interface{}(config.Config.JWTAuthUserProperty), &jwt.Token{})
^
pkg/handler/subject_test.go:29:31: SA1029: should not use built-in type string as key for value; define your own type to avoid collisions (staticcheck)
ctx = context.WithValue(ctx, interface{}(config.Config.JWTAuthUserProperty), &jwt.Token{
^
make: *** [Makefile:66: verify_lint] Error 1
Exited with code exit status 2
```

Fix golangci-lint for context string key unittest

---

pkg/handler/crud.go

This change does an explicit check for a RecordNotFound error and returns a 404 only in that case; returning 500 in other cases
Fixes #317 
> Currently, in the case that the database is removed from behind a running instance of flagr (network connection, password change, etc) the application returns a 404 to a GET request on localhost:13480/api/v1/flags/1000
Tested locally by starting up an instance of flagr, verifying functionality, removing the backing database and then attempting to get the same flag again.
I don't believe there are tests covering this particular kind of failure case in `crud_tests.go` but I might have missed them - please do point it out and I'll add them if so

Add better error checking around 404s and actual database errors

---

pkg/handler/crud.go
pkg/handler/crud_test.go

Fix #342 
Tested locally.
- `/api/v1/flags` returns all
- `/api/v1/flags?enabled=true` returns enabled ones
- `/api/v1/flags?enabled=false` returns disabled ones
I think the boolean parameter binding from go-swagger also allows `?enabled=t` or `?enabled=f`.

Fix enabled query param

---

pkg/util/util.go
pkg/util/util_test.go

Add support for `:` and `.` characters.
Fixes #347

Support additional characters for flag keys

---

docs/flagr_env.md
pkg/config/env.go
pkg/config/middleware.go
pkg/config/middleware_test.go

Add optional basic auth support to keep the interface from being publicly available.
- Added new environment variables to enable and configure basic authentication. Disabled by default.
- When enabled, adds a new middleware to support basic auth
- Respect whitelist of paths (prefix or exact match)
- This solves the issue of hosting flagr where it is reachable on the public internet but you do not want outside users to access the web interface.
- Deployed to our hosting provider and manually tested basic auth prompt with various env values.

Add basic auth support for interface

---

docs/api_docs/bundle.yaml
go.mod
pkg/handler/export.go
pkg/handler/export_test.go
swagger/export_sqlite.yaml
swagger_gen/restapi/embedded_spec.go
swagger_gen/restapi/operations/export/get_export_sqlite_parameters.go
swagger_gen/restapi/operations/export/get_export_sqlite_urlbuilder.go
vendor/modules.txt

Sometimes the snapshots table is just too big to download, wanted to introduce a query param that can help to reduce the sqlite export size. This is fully backward compatible.
unit tests and integration test

Add exclude_snapshots query param to export/sqlite

---

pkg/config/env.go
pkg/config/middleware.go

Add configurable option to exclude URLs from verbose middleware logging
We added `MiddlewareVerboseLoggerExcludeURLs`  env where excluded urls can be specified as a list of string comma separated. We configure the middleware logging with this configuration setting.
Currently we have integrated Flagr on our infrastructure and we wanted to remove logging entries for not relevant urls like health check or metrics. So we can focus on relevant ones.

Config option to exclude URLs from verbose middleware logging

---

README.md

Adds a list of currently existing client libraries to the README file for the overall Flagr project.
This makes it clear which languages might still benefit from implementation, and allows a central place to find client libraries even if they're not officially supported (a field could be added to denote official support later).
Markdown preview within GitHub.
None of the above. Minor docs change.

Add list of client libraries to README

---

browser/flagr-ui/src/components/FlagHistory.vue

Remove margin on `.compact` class to add more space between timestamp and updated by section 
Before
After removing margin
I've setup Flagr using HTTP Header auth, when I saw the Flag history page, I noticed that the gap between snapshot's timestamp and updated by is too narrow. Removing margin seems solve this issue. Also this removal won't affect snapshot without updated by section as it's using different CSS class
Tested on local using these browsers : 
- Google Chrome Version 85.0.4183.83 (Official Build) (64-bit)
- Firefox 80.0.1 (64-bit)
- Safari Version 13.1.2 (15609.3.5.1.3)
UI change

Remove margin on compact class

---

.circleci/config.yml
Makefile
pkg/handler/eval_test.go
pkg/handler/fixture.go

Add `go test -bench` for critical flag evaluation code path, so that we can track of performance regression.

Add benchmark

---

.circleci/config.yml
Dockerfile
go.mod
integration_tests/Dockerfile-Integration-Test

Keep up with the latest go version. It slightly reduces the binary size.

Bump to go1.15

---

pkg/handler/eval.go
pkg/handler/eval_cache.go
pkg/handler/eval_cache_fetcher.go
pkg/handler/eval_test.go
pkg/handler/fixture.go

- Fix https://github.com/checkr/flagr/issues/398
- Refactor all the cache with atomic.Value for concurrent access and reduce lock contention
- Refactor ratelimiter to sync.Map to reduce the rare chance of race condition
- Fix the logic of merging tags in `GetByTags` so that we are just merging into the temp variable instead of changing the protected cache
- unit tests
- integration tests
- manual tests
- benchmark

Refactor eval cache with atomic.Value

---

docs/api_docs/bundle.yaml
integration_tests/test.sh
pkg/handler/eval.go
pkg/handler/eval_cache.go
pkg/handler/eval_cache_test.go
swagger/index.yaml
swagger_gen/models/eval_context.go
swagger_gen/models/evaluation_batch_request.go
swagger_gen/restapi/embedded_spec.go

Finding flags to be evaluated using tags allow to pass ANY/ALL tag matching as operator
Just support a new enum value `ANY` or `ALL` to determine which flags matches the tags the default is `ANY`. `ALL` just filter out results applying tags one after the other.
The main idea of the change is to allow to pass `flagsTagsOperator` on batch evaluation requests so we can handle scenarios where each tag used to describe the flags are independent so we could want to match flags which contains all the tags passed. Currently, tags are considered as any tag in the flags make the match.
We have tags determining the ownership of the flags, and some teams group flags inside other tags and we have some generic rules to naming it.
- ownership -> `owner:team-name`
- batch -> `batch:batch-name`
So as …

Evaluation with FlagTagsOperator to match any or all tags

---

pkg/config/env.go
pkg/handler/data_recorder_kafka.go
pkg/handler/data_recorder_kafka_test.go
pkg/handler/export.go

This adds variables for authentication and enabling simple ssl without specifying certificates and others
This should enable to use kafka with providers like confluent which uses sasl_plain over ssl.
I've tested it against our cluster which requires authentication with and ssl

Add support for kafka auth using SASL with PLAIN mechanism

---

browser/flagr-ui/src/components/Flags.vue

In the home page we currently have a first row to add new flags and a second row to search for flags. We have modified the second row in order to show a dropdown list in which we can see the values \[`All the flags`, `Enabled flags`, `Disabled flags`\] being the value `All the flags` the one selected by default.
As the [current API](https://checkr.github.io/flagr/api_docs/#operation/findFlags) supports the boolean parameter `enabled` to filter flags by enabled and disabled, we only needed to change the GUI to add the filter.
The number of flags is growing and as this is a service shared by all of our customers, it is expected it will continue growing in the future. To do it easier to work with Flagr we want to provide a way of filtering flags by status (enabled / disabled).
1. I added …

Add dropdown by state to filter flags

---

integration_tests/docker-compose.yml

Fix https://github.com/checkr/flagr/issues/442
The reason is that https://stackoverflow.com/a/66910240, removing `MYSQL_USER` set in the docker-compose file fixes the problem, note that `root` is automatically created.

Fix integration tests
